dataset_yaml: "config/doclaynet_yolo.yaml"

model: "yolo11n.pt"        # 모델 이름 
task: "detect"             # detect / segment / pose 등 (여기서는 detect)

train:
  epochs: 10
  imgsz: 640
  batch: 4
  workers: 4
  device: "cuda"

  project: "runs/doclaynet"
  name: "yolo11n"

# augmentation을 YAML에서 관리하고 싶다면 나중에 추가 가능
